apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../base

images:
  - name: ws-api-service
    newName: gcr.io/google-sampl
    newTag: v0.8.0
  - name: gcr-cartservice
    newName: gcr.io/google-samples/microservices-demo/cartservice
    newTag: v0.8.0


