apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app-prod
resources:
  - ../../apps-config
images:
  - name: ws-api-service # Check 
    newName: myoko2026/ws-api-service
    newTag: v2026.01.17
  - name: gcr-cartservice
    newName: gcr.io/cartservice
    newTag: v0.8.0
